source 'https://rubygems.org'

gem 'sinatra', '~> 2.2', '>= 2.2.2'

gem 'thin', '~> 1.8', '>= 1.8.1'

gem 'rack-contrib', '~> 2.3'

gem 'rack-cors', '~> 1.1', '>= 1.1.1'

gem 'activerecord', '~> 7.0', '>= 7.0.3.1'

gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.25'

gem 'rake', '~> 13.0', '>= 13.0.6'

gem 'sqlite3', '~> 1.4', '>= 1.4.4'

gem 'require_all', '~> 3.0'

gem 'rest-client', '~> 2.1'

gem 'faker', '~> 2.23'

group :development do
  gem 'pry', '~> 0.14.1'
  gem "rerun"
end

group :test do
  gem 'database_cleaner', '~> 2.0', '>= 2.0.1'
  gem 'rack-test', '~> 2.0', '>= 2.0.2'
  gem 'rspec', '~> 3.11'
  gem 'rspec-json_expectations', '~> 2.2'
end